const CANVAS_WIDTH = 1200 / 1.2;
const CANVAS_HEIGHT = 650 / 1.2;
const ARROW_RIGHT = 39;
const ARROW_DOWN = 40;
const ARROW_LEFT = 37;
const ARROW_UP = 38;
const SPACE_BAR = 32;
const ENTER_KEY = 13;
const P_KEY = 80;
const GRAVITY = 0.2;
let batty;
let pumpkino;
let rocket;
const PLAYER_WIDTH = 70 / 1.2;
const PLAYER_HEIGHT = 70 / 1.2;
let backgroundForest;
let backgroundPumpkin;
let backgroundRockets;
let backgroundGameOver;
const batKills = document.querySelector("h2 span");
const pumpkinEat = document.querySelector("h3 span");
